### ISSUE TITLE
VTI15: cannot import name setResumePoint

### ISSUE THREAD

**Issue by ltspicer** [CommanderData2338/SRFMediathek#1]
deleted by user

**Comment by CommanderData2338** [comment]
Was müllst du mich mit Issues & Pull requests zu?

Ich geh mal davon aus das du treki von boxpirates forum bist wo mir ein link zu geschickt wurde
mit der schönen Forderung SRF Mediathek V0.7 zu veröffentlichen

erstens ich habe dir nicht die Erlaubnis gegeben an meinen Plugins herumzupfuschen noch hast du irgendwelche Forderungen zu stellen

was Mediaportal hat oder hatte interessiert mich nicht da musst du dhwz anschreiben meine Plugins  haben einen anderen Focus als Mediaportal deswegen mache bitte keinen Apfel mit Birnen Vergleich

ich kann dir aber jetzt schon schreiben das ich in Zukunft die zusätzlichen Sender einbauen werde und auch den Audio Bereich ausbaue wenn ich die Lust und zeit finde

wenn du Verbesserungsvorschläge,Anregungen hast bitte im OpenATV Forum schreiben dann kann ich darauf eingehen

und bitte müll mich hier nicht wieder mit Pull requests zu D.A.N.K.E

**Comment by ltspicer** [comment]
Ich möchte mich in aller Form entschuldigen.
Der PullRequest hab ich falsch verstanden und möchte das auch gerne rückgängig machen.
Ich hab zudem falsch agiert, weil ich dachte, alles in github wenn geklont angepasst werden dürfte (was ich bei meinen Contents zulasse).
Ich habe den Klon gelöscht (der war öffentlich, was ich eigentlich nicht wollte).
Nochmal. Ich bin kein Spamer.
Ich hoffe, Du vergibst mir.
