### ISSUE TITLE
Sport Live-Streams

### ISSUE THREAD

**Issue by ltspicer** [CommanderData2338/SRFMediathek#3]
Schnell eine Frage.
Ist es normal, dass unter Sport die Live-Streams nicht funktionieren oder liegt es an meiner Konfiguration/Konstellation?
Ich habe eine richtige schweizer IP, nicht bloss eine VPN.

Ist aber nicht wirklich schlimm für mich. Es interessiert mich nur, ob das laufen sollte.
Ansonsten bin ich mit diesem Plugin happy!

**Comment by CommanderData2338** [comment]
Hallo Daniel 
die Live-Streams sind DRM geschützt da kann ich aktuell leider nichts machen
aber ich kann schon schreiben mit der nächsten Version 0.7 kommen die von dir gewünschten Sender RTS, RSI, RTR, SWI 

LG Alex

**Comment by ltspicer** [comment]
Das ist super. Vielen Dank.
Das mit den Live-Streams hab ich mir halbers gedacht.
Wollte nur sicher gehn, dass das Problem nicht bei mir liegt  ;)
